// pages/add-friend/add-friend.js
Page({
  data: {
    placeholder:'请输入',
    list:[
      {
        friendID:'1',
        friendImg:'/assets/images/author.jpg',
        friendName:'张三',
        recive:1,
        Findex:'Z'
      },
      {
        friendID:'2',
        friendImg:'/assets/images/author.jpg',
        friendName:'李四',
        Findex:'L'
      },
      {
        friendID:'3',
        friendImg:'/assets/images/author.jpg',
        friendName:'王五',
        Findex:'W'
      },
      {
        friendID:'4',
        friendImg:'/assets/images/author.jpg',
        friendName:'A王五',
        Findex:'A'
      },
      {
        friendID:'5',
        friendImg:'/assets/images/author.jpg',
        friendName:'张',
        Findex:'Z'
      },
      {
        friendID:'6',
        friendImg:'/assets/images/author.jpg',
        friendName:'陈',
        Findex:'C'
      },
      {
        friendID:'7',
        friendImg:'/assets/images/author.jpg',
        friendName:'李',
        Findex:'L'
      },
      {
        friendID:'8',
        friendImg:'/assets/images/author.jpg',
        friendName:'杨',
        Findex:'Y'
      },
      {
        friendID:'9',
        friendImg:'/assets/images/author.jpg',
        friendName:'杨二',
        Findex:'Y'
      },
      {
        friendID:'10',
        friendImg:'/assets/images/author.jpg',
        friendName:'黄',
        Findex:'H'
      },
      {
        friendID:'11',
        friendImg:'/assets/images/author.jpg',
        friendName:'刘',
        Findex:'L'
      },
      {
        friendID:'12',
        friendImg:'/assets/images/author.jpg',
        friendName:'赵',
        Findex:'Z'
      },
      {
        friendID:'13',
        friendImg:'/assets/images/author.jpg',
        friendName:'吴',
        Findex:'W'
      },
      {
        friendID:'14',
        friendImg:'/assets/images/author.jpg',
        friendName:'郑',
        Findex:'Z'
      },
      {
        friendID:'15',
        friendImg:'/assets/images/author.jpg',
        friendName:'林',
        Findex:'L'
      },
      {
        friendID:'16',
        friendImg:'/assets/images/author.jpg',
        friendName:'朱',
        Findex:'Z'
      },
      {
        friendID:'17',
        friendImg:'/assets/images/author.jpg',
        friendName:'徐',
        Findex:'X'
      },
      {
        friendID:'18',
        friendImg:'/assets/images/author.jpg',
        friendName:'孙',
        Findex:'S'
      },
      {
        friendID:'19',
        friendImg:'/assets/images/author.jpg',
        friendName:'周',
        Findex:'Z'
      },
      {
        friendID:'20',
        friendImg:'/assets/images/author.jpg',
        friendName:'何',
        Findex:'H'
      },
      {
        friendID:'21',
        friendImg:'/assets/images/author.jpg',
        friendName:'郭',
        Findex:'G'
      },
      {
        friendID:'22',
        friendImg:'/assets/images/author.jpg',
        friendName:'马',
        Findex:'M'
      },
      {
        friendID:'23',
        friendImg:'/assets/images/author.jpg',
        friendName:'梁',
        Findex:'L'
      },
      {
        friendID:'24',
        friendImg:'/assets/images/author.jpg',
        friendName:'罗',
        Findex:'L'
      },
      {
        friendID:'25',
        friendImg:'/assets/images/author.jpg',
        friendName:'高',
        Findex:'G'
      },
      {
        friendID:'26',
        friendImg:'/assets/images/author.jpg',
        friendName:'胡',
        Findex:'H'
      },
      {
        friendID:'27',
        friendImg:'/assets/images/author.jpg',
        friendName:'谢',
        Findex:'X'
      },
      {
        friendID:'28',
        friendImg:'/assets/images/author.jpg',
        friendName:'邓',
        Findex:'D'
      },
      {
        friendID:'29',
        friendImg:'/assets/images/author.jpg',
        friendName:'周',
        Findex:'Z'
      },
      {
        friendID:'30',
        friendImg:'/assets/images/author.jpg',
        friendName:'何',
        Findex:'H'
      },
      {
        friendID:'31',
        friendImg:'/assets/images/author.jpg',
        friendName:'许',
        Findex:'X'
      },
      {
        friendID:'32',
        friendImg:'/assets/images/author.jpg',
        friendName:'姚',
        Findex:'Y'
      },
      {
        friendID:'33',
        friendImg:'/assets/images/author.jpg',
        friendName:'蔡',
        Findex:'C'
      },
      {
        friendID:'34',
        friendImg:'/assets/images/author.jpg',
        friendName:'丁',
        Findex:'D'
      },
      {
        friendID:'35',
        friendImg:'/assets/images/author.jpg',
        friendName:'冯',
        Findex:'F'
      },
      {
        friendID:'36',
        friendImg:'/assets/images/author.jpg',
        friendName:'宋',
        Findex:'S'
      },
      {
        friendID:'37',
        friendImg:'/assets/images/author.jpg',
        friendName:'余',
        Findex:'Y'
      },
      {
        friendID:'38',
        friendImg:'/assets/images/author.jpg',
        friendName:'唐',
        Findex:'T'
      }
    ],
    addFriend: true,
    nochange: true
  },

  onLoad: function (options) {

  },

  goDetail(e){
    wx.navigateTo({
      url: '/pages/friend-detail/friend-detail?id='+e.currentTarget.dataset.id,
      success: (result)=>{
        
      },
      fail: ()=>{},
      complete: ()=>{}
    });
  }

})